# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ollector.proto\"\"\n\nCollectReq\x12\x14\n\x0cnum_episodes\x18\x01 \x01(\x05\"\x9d\x01\n\x07\x45pisode\x12\r\n\x05types\x18\x01 \x03(\x05\x12\x11\n\tdiscounts\x18\x02 \x03(\x02\x12\x0f\n\x07rewards\x18\x03 \x03(\x02\x12\x12\n\nobs_market\x18\x04 \x03(\x02\x12\x14\n\x0cobs_stateful\x18\x05 \x03(\x02\x12\x12\n\nnext_types\x18\x06 \x03(\x05\x12\x0f\n\x07\x61\x63tions\x18\x07 \x03(\x03\x12\x10\n\x08ps_infos\x18\x08 \x01(\x0c\",\n\x16NotifyPolicyUpdatedReq\x12\x12\n\nredis_addr\x18\x01 \x01(\t\"\x19\n\x17NotifyPolicyUpdatedResp\"\x0c\n\nEnvSpecReq\"T\n\x0b\x45nvSpecResp\x12\x18\n\x10observation_spec\x18\x01 \x01(\x0c\x12\x13\n\x0b\x61\x63tion_spec\x18\x02 \x01(\x0c\x12\x16\n\x0etime_step_spec\x18\x03 \x01(\x0c\x32\xa7\x01\n\x0e\x43ollectService\x12\"\n\x07\x63ollect\x12\x0b.CollectReq\x1a\x08.Episode0\x01\x12J\n\x15notify_policy_updated\x12\x17.NotifyPolicyUpdatedReq\x1a\x18.NotifyPolicyUpdatedResp\x12%\n\x08\x65nvspecs\x12\x0b.EnvSpecReq\x1a\x0c.EnvSpecRespb\x06proto3')



_COLLECTREQ = DESCRIPTOR.message_types_by_name['CollectReq']
_EPISODE = DESCRIPTOR.message_types_by_name['Episode']
_NOTIFYPOLICYUPDATEDREQ = DESCRIPTOR.message_types_by_name['NotifyPolicyUpdatedReq']
_NOTIFYPOLICYUPDATEDRESP = DESCRIPTOR.message_types_by_name['NotifyPolicyUpdatedResp']
_ENVSPECREQ = DESCRIPTOR.message_types_by_name['EnvSpecReq']
_ENVSPECRESP = DESCRIPTOR.message_types_by_name['EnvSpecResp']
CollectReq = _reflection.GeneratedProtocolMessageType('CollectReq', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTREQ,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:CollectReq)
  })
_sym_db.RegisterMessage(CollectReq)

Episode = _reflection.GeneratedProtocolMessageType('Episode', (_message.Message,), {
  'DESCRIPTOR' : _EPISODE,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:Episode)
  })
_sym_db.RegisterMessage(Episode)

NotifyPolicyUpdatedReq = _reflection.GeneratedProtocolMessageType('NotifyPolicyUpdatedReq', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFYPOLICYUPDATEDREQ,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:NotifyPolicyUpdatedReq)
  })
_sym_db.RegisterMessage(NotifyPolicyUpdatedReq)

NotifyPolicyUpdatedResp = _reflection.GeneratedProtocolMessageType('NotifyPolicyUpdatedResp', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFYPOLICYUPDATEDRESP,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:NotifyPolicyUpdatedResp)
  })
_sym_db.RegisterMessage(NotifyPolicyUpdatedResp)

EnvSpecReq = _reflection.GeneratedProtocolMessageType('EnvSpecReq', (_message.Message,), {
  'DESCRIPTOR' : _ENVSPECREQ,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:EnvSpecReq)
  })
_sym_db.RegisterMessage(EnvSpecReq)

EnvSpecResp = _reflection.GeneratedProtocolMessageType('EnvSpecResp', (_message.Message,), {
  'DESCRIPTOR' : _ENVSPECRESP,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:EnvSpecResp)
  })
_sym_db.RegisterMessage(EnvSpecResp)

_COLLECTSERVICE = DESCRIPTOR.services_by_name['CollectService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COLLECTREQ._serialized_start=19
  _COLLECTREQ._serialized_end=53
  _EPISODE._serialized_start=56
  _EPISODE._serialized_end=213
  _NOTIFYPOLICYUPDATEDREQ._serialized_start=215
  _NOTIFYPOLICYUPDATEDREQ._serialized_end=259
  _NOTIFYPOLICYUPDATEDRESP._serialized_start=261
  _NOTIFYPOLICYUPDATEDRESP._serialized_end=286
  _ENVSPECREQ._serialized_start=288
  _ENVSPECREQ._serialized_end=300
  _ENVSPECRESP._serialized_start=302
  _ENVSPECRESP._serialized_end=386
  _COLLECTSERVICE._serialized_start=389
  _COLLECTSERVICE._serialized_end=556
# @@protoc_insertion_point(module_scope)
