# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ollector.proto\"\"\n\nCollectReq\x12\x14\n\x0cnum_episodes\x18\x01 \x01(\x05\"\x89\x01\n\x07\x45pisode\x12\r\n\x05types\x18\x01 \x03(\x05\x12\x11\n\tdiscounts\x18\x02 \x03(\x02\x12\x0f\n\x07rewards\x18\x03 \x03(\x02\x12\x14\n\x0cobservations\x18\x04 \x03(\x02\x12\x12\n\nnext_types\x18\x05 \x03(\x05\x12\x0f\n\x07\x61\x63tions\x18\x06 \x03(\x03\x12\x10\n\x08ps_infos\x18\x07 \x01(\x0c\"@\n\x0fUpdatePolicyReq\x12\x1a\n\x12train_step_counter\x18\x01 \x01(\x0c\x12\x11\n\tvariables\x18\x02 \x01(\x0c\"\x12\n\x10UpdatePolicyResp\"\x0c\n\nEnvSpecReq\"T\n\x0b\x45nvSpecResp\x12\x18\n\x10observation_spec\x18\x01 \x01(\x0c\x12\x13\n\x0b\x61\x63tion_spec\x18\x02 \x01(\x0c\x12\x16\n\x0etime_step_spec\x18\x03 \x01(\x0c\x32\x91\x01\n\x0e\x43ollectService\x12\"\n\x07\x63ollect\x12\x0b.CollectReq\x1a\x08.Episode0\x01\x12\x34\n\rupdate_policy\x12\x10.UpdatePolicyReq\x1a\x11.UpdatePolicyResp\x12%\n\x08\x65nvspecs\x12\x0b.EnvSpecReq\x1a\x0c.EnvSpecRespb\x06proto3')



_COLLECTREQ = DESCRIPTOR.message_types_by_name['CollectReq']
_EPISODE = DESCRIPTOR.message_types_by_name['Episode']
_UPDATEPOLICYREQ = DESCRIPTOR.message_types_by_name['UpdatePolicyReq']
_UPDATEPOLICYRESP = DESCRIPTOR.message_types_by_name['UpdatePolicyResp']
_ENVSPECREQ = DESCRIPTOR.message_types_by_name['EnvSpecReq']
_ENVSPECRESP = DESCRIPTOR.message_types_by_name['EnvSpecResp']
CollectReq = _reflection.GeneratedProtocolMessageType('CollectReq', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTREQ,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:CollectReq)
  })
_sym_db.RegisterMessage(CollectReq)

Episode = _reflection.GeneratedProtocolMessageType('Episode', (_message.Message,), {
  'DESCRIPTOR' : _EPISODE,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:Episode)
  })
_sym_db.RegisterMessage(Episode)

UpdatePolicyReq = _reflection.GeneratedProtocolMessageType('UpdatePolicyReq', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPOLICYREQ,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:UpdatePolicyReq)
  })
_sym_db.RegisterMessage(UpdatePolicyReq)

UpdatePolicyResp = _reflection.GeneratedProtocolMessageType('UpdatePolicyResp', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPOLICYRESP,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:UpdatePolicyResp)
  })
_sym_db.RegisterMessage(UpdatePolicyResp)

EnvSpecReq = _reflection.GeneratedProtocolMessageType('EnvSpecReq', (_message.Message,), {
  'DESCRIPTOR' : _ENVSPECREQ,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:EnvSpecReq)
  })
_sym_db.RegisterMessage(EnvSpecReq)

EnvSpecResp = _reflection.GeneratedProtocolMessageType('EnvSpecResp', (_message.Message,), {
  'DESCRIPTOR' : _ENVSPECRESP,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:EnvSpecResp)
  })
_sym_db.RegisterMessage(EnvSpecResp)

_COLLECTSERVICE = DESCRIPTOR.services_by_name['CollectService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COLLECTREQ._serialized_start=19
  _COLLECTREQ._serialized_end=53
  _EPISODE._serialized_start=56
  _EPISODE._serialized_end=193
  _UPDATEPOLICYREQ._serialized_start=195
  _UPDATEPOLICYREQ._serialized_end=259
  _UPDATEPOLICYRESP._serialized_start=261
  _UPDATEPOLICYRESP._serialized_end=279
  _ENVSPECREQ._serialized_start=281
  _ENVSPECREQ._serialized_end=293
  _ENVSPECRESP._serialized_start=295
  _ENVSPECRESP._serialized_end=379
  _COLLECTSERVICE._serialized_start=382
  _COLLECTSERVICE._serialized_end=527
# @@protoc_insertion_point(module_scope)
